# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker run -v $(System.DefaultWorkingDirectory):/workspace -w /workspace python:2.7 python add.py
  displayName: 'Run add.py in Docker with Python 2.7'

- script: |
    docker run python:2.7 python -c "print('AZURE PIPELINE')"
    docker run python:2.7 python -c "print('CONTINUOUS INTEGRATION & CONTINUOUS DEPLOYMENT')"
  displayName: 'Run inline script in Docker with Python 2.7'

